### ISSUE TITLE
Implementing the smart TrafficLightManager

### ISSUE THREAD

**Issue by AdamElgressy** [TechnionYearlyProject/BTW#129]
Implementing the researched smart TrafficLightManager

expected time: 12 hours
actual time: 1(Adam) + X(Sharon)

**Comment by SharonHadar** [comment]
finished to implement
it took 40 hours (including debugging)
the commits are:
47cdf7b16c7c0da8b9d1d541fb02dfb5b8d4aa2d
3f7199018d3f4d2232aa28c0ca2c598eea835f83
4a110c59bf43e64439f8b1f9cb0359fc40f0e772
e58919cd9e865e9c70487516dbfd553a1b43940c
8103425fb06599ff0738ded3388e7a992db07abb
