### ISSUE TITLE
Enhance basic gui properties

### ISSUE THREAD

**Issue by AdamElgressy** [TechnionYearlyProject/BTW#59]
add all of first beta-testing comments related to GUI:

- [x] add back button on simulation screen
- [ ] add scroll option in the "load map" option to have all of saved maps in DB
- [ ] change the add vehicle interaction: make to options, use file which describes vehicles in a certain format we will choose, or use the box to add random vehicles to the city (change the box background to be visible).

**Comment by AdamElgressy** [comment]
consider splitting to several issues

**Comment by shaymichaeli** [comment]
opened #69 (Data Base side) and #70 (UI side) for the second bullet.

**Comment by orelkan** [comment]
opened #74 that relates to first bullet

**Comment by orelkan** [comment]
opened #90 that relates to third bullet

**Comment by orelkan** [comment]
done
