### ISSUE TITLE
Fix bug - Displaying the home screen is slow

### ISSUE THREAD

**Issue by orelkan** [TechnionYearlyProject/BTW#98]
Because of the new code in the initialize function of the HomeController class, every time the home screen is generated it connects to the Database and this makes the action slower, especially each back button press triggers this and it hinders the application's performance. Need to make a more elegant solution.

**Comment by shaymichaeli** [comment]
The current code is temporary. The is no need to create BTWDataBaseImpl every time,
But we most connect to the DB server at least once in order to get map names

**Comment by orelkan** [comment]
Issue is closed for now. bug is fixed
